version: "3.3"

services:
  client:
    image: ideadapt/todomvc-client:latest
    networks:
      - todonet

  server:
    image: ideadapt/todomvc-java-server
    networks:
      - todonet
    environment:
      # db is the docker-network internal DNS name of the db service
      - JDBC_URI=jdbc:mysql://db:3306/todo

  db:
    image: mysql:8.0
    # Uncomment to make database accessible from host system
    #    ports:
    #      - 3306:3306
    networks:
      - todonet
    # Variables values have to be set from outside, e.g. via .env file
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./db-data/v1:/docker-entrypoint-initdb.d

  # Reverse proxy. The only service with exposed port
  web:
    image: nginx
    depends_on:
      - client
      - server
    networks:
      - todonet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8000"

networks:
  todonet:
    driver: bridge
